import { Button} from "std-widgets.slint";
import { InWindowTopBar} from "topBar.slint";
// import  "./fonts/ark-pixel-10px-proportional.ttc";
// import "./fonts/VonwaonBitmap-12px.ttf";
import "./fonts/fusion-pixel-10px-proportional.ttc";
import { InWindowTopBar } from "TopBar.slint";


component CloseButton inherits Rectangle
{
    width: 14px;
    height: 14px;
    border-radius: 3px;
    background: root.border-color;
    touch := TouchArea
    {
        clicked => 
        {

        }
    }
}



component NexusButton inherits Button
{
    

    clicked => 
    { 
        self.text = self.text + "!";

    }

}


export component MainWindow inherits Window 
{

    //Title of the window
    
    title: "Nexus Music";
    icon: @image-url("../resources/icons/Nexus_logo_s.png");
    background: @linear-gradient(0deg,#000000 0%,#7b6c6c 50%,#ffc5c5 100%);
    no-frame: true;

    height: 720px;
    width: 1080px;
    

    in property <int> text_count : 1;
    in-out property <string> app_text;
    in property <string> init_content: "Initialized";
    in-out property <string> font-family;

    default-font-family: font-family;

    callback button1-click <=> btn.clicked;
    callback window-init(string);
    callback window-close();

    init => 
    {
        window-init(init_content);
        font-family = "Fusion Pixel 10px Proportional zh_hans";
    }

    window-init(init_text) => 
    {
        app_text = init_text;
    }

    VerticalLayout
    {

        spacing: 5px;

        InWindowTopBar 
        {
            title: root.title;
            font: "Fusion Pixel 10px Proportional zh_hans";
            close => 
            {
                window-close();
            }
        }

        VerticalLayout
        {
            padding: 5px;

            Text 
            {
                height: 600px;
                font-size: 50px;
                font-family: "Fusion Pixel 10px Proportional zh_hans";

                text: app_text + " 你好！";
            }

            HorizontalLayout
            {
                spacing: 5px;
                btn := NexusButton // name the NexusButton to "btn"
                {
                    width: 100px;
                    opacity:0.5;
                    text: "Nexus";
                }

                btn2 := NexusButton
                {
                    width: 100px;
                    opacity:0.5;
                    text: "";
                }
            }
        }

        

        

    }    
}