import "./fonts/fusion-pixel-10px-proportional.ttc";

export component InWindowTopBar inherits VerticalLayout
{
    height: 25px;
    width: 1080px;

    in property <string> title;
    in-out property <string> font;
    in property <brush> titleColor;

    // if mouse button is pressed.
    property <bool> drag-area-pressed: false;
    // record the position of the press.
    property <length> drag-area-down-x: 0;
    property <length> drag-area-down-y: 0;

    callback move-window(length, length);
    callback close();

    Rectangle 
    {
        height: 25px;
        background: #ffc5c5;

        HorizontalLayout 
        {

            padding-left: 5px;
            padding-right: 5px;
            spacing: 5px;

            Image 
            {
                y: 3px;
                width: 18px;
                height: 18px;

                image-fit:fill;
                image-rendering: smooth;

                source: @image-url("../resources/icons/Nexus_logo_s.png");

            }

            ApplicationTitle := Text 
            {
                font-family: font;
                text: title;
                font-size: 15px;
                color: white;
                TouchArea 
                {
                    moved => 
                    {
                        move-window(self.mouse-x - drag-area-down-x, 
                                    self.mouse-y - drag-area-down-y);
                    }
                    pointer-event(e) => 
                    {
                        drag-area-pressed = e.kind == PointerEventKind.down;
                        drag-area-down-x = self.mouse-x;
                        drag-area-down-y = self.mouse-y;
                    }
                }
            }

            

            
            

            Rectangle 
            {
                y: 5px;
                width: 14px;
                height: 14px;
                border-radius: 3px;
                background: darkred;

                opacity: 1;

                touch := TouchArea
                {
                    clicked => 
                    { 
                        close() 
                    }
                }

                Text 
                {
                    text: "X";
                    color:touch.has-hover? touch.pressed? red : pink : white;
                }

            }

        }
    }

    
    

    


}