import "./fonts/fusion-pixel-10px-proportional.ttc";

export component InWindowTopBar inherits VerticalLayout
{
    height: 25px;
    width: 1080px;

    in property <string> title;
    in-out property <string> font;
    in property <brush> titleColor;

    // if mouse button is pressed.
    property <bool> drag-area-pressed: false;
    // record the position of the press.
    property <length> drag-area-down-x: 0;
    property <length> drag-area-down-y: 0;
    property <length> corner-radius: 3px;

    callback move-window(length, length);
    callback close();

    Rectangle 
    {
        height: root.height;
        background: #ffc5c5;
        border-radius: corner-radius;

        HorizontalLayout 
        {

            //padding-right: 5px;
            spacing: 5px;


            Rectangle 
            {
                width: root.height;
                height: root.height;
                border-radius: corner-radius;
                clip: true;
                Image 
                {

                    width: root.height;
                    height: root.height;

                    image-fit:fill;
                    image-rendering: smooth;
                    

                    source: @image-url("../resources/icons/Nexus_logo_s.png");

                }
            }
            

            ApplicationTitle := Text 
            {
                font-family: font;
                text: title;
                font-size: 15px;
                color: white;
                TouchArea 
                {
                    moved => 
                    {
                        move-window(self.mouse-x - drag-area-down-x, 
                                    self.mouse-y - drag-area-down-y);
                    }
                    pointer-event(e) => 
                    {
                        drag-area-pressed = e.kind == PointerEventKind.down;
                        drag-area-down-x = self.mouse-x;
                        drag-area-down-y = self.mouse-y;
                    }
                }
            }

            

            
            

            Rectangle 
            {
                //y:root.height*2%;
                width: root.height;
                height: root.height;
                
                border-radius: corner-radius;
                background: pink;

                opacity: 1;

                touch := TouchArea
                {
                    clicked => 
                    { 
                        close() 
                    }
                }

                Text 
                {
                    text: "X";
                    font-size: root.height * 80%;
                    color:touch.has-hover? touch.pressed? red : darkred : white;
                }

            }

        }
    }

    
    

    


}